# See https://stylelint.io/user-guide/rules/list
# Also https://github.com/kristerkari/stylelint-scss#list-of-rules

extends:
  - stylelint-config-standard-scss
  - stylelint-prettier/recommended
plugins:
  - stylelint-prettier

rules:
  # Default rules:
  #   - https://github.com/stylelint-scss/stylelint-config-standard-scss/blob/main/index.js
  #   - https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/master/index.js
  #   - https://github.com/stylelint/stylelint-config-standard/blob/main/index.js
  #   - https://github.com/stylelint/stylelint-config-recommended/blob/main/index.js
  #   - https://github.com/prettier/stylelint-config-prettier/blob/master/src/index.js

  # possible errors (these are all on by default)
  no-descending-specificity: null

  # limit language features
  color-named: always-where-possible
  custom-property-pattern: null
  declaration-no-important: true
  function-url-no-scheme-relative: true
  selector-class-pattern: null
